### ISSUE TITLE
Can make recommendations as soon as 5 entries (with 100+ rec with even a single entry)

### ISSUE THREAD

**Issue by ethulin** [mefee/mefee#15]
I think the current system waits for 20 entries?

I think we can reasonably make recommendations (as in, if above the red line) as 5 entries. The good thing about using that 90% CI level is that it accounts for not having a lot of data and therefore being more conservative.

Also, we should make recommendations immediately if someone is above 100f, regardless of how many entries.

**Comment by harry-peirse** [comment]
Great, thanks. I'll reduce the threshold to 5.
It already recommends immediately at 100 or greater.

**Comment by harry-peirse** [comment]
Done
