### ISSUE TITLE
Feedback to consider:

### ISSUE THREAD

**Issue by harry-peirse** [mefee/mefee#17]
(from a colleague)

-Change the tab Input to 'Temperature Recorder' (Harry says: maybe something shorter for mobile devices?)
-When looking at the results, it always says Healthy when 200F clearly isnt! (Harry says: this is a bug! there wasn't enough data for analysis to show and validation to kick in)
-Make it clear whether you share these results or not? (Harry says: need to document some sort of data policy?)

**Comment by ethulin** [comment]
Re:tab - Maybe "Temp Input" or "Record Temp". I don't think temperature recorder works very well, as I think the entire app might be thought of that way.

On the last point, I heard a similar concern.

I wonder if we can just really simply write one and ad a link to the bottom:

Information we collect:
- Your gmail address
- Your temperature recording data
- Your IP address
- anything else?

Information we disclose:
For research purposes, we may disclose anonymized temperature recording data

Information we do _not_ disclose:
We do not disclose any identifiable information, linked or unlinked to your temperature data, including your gmail address or your IP address

Requesting we delete your information:
If you would like us to delete your information, please send us a request at privacy@mefee.org from the gmail address associated with your account.

**Comment by harry-peirse** [comment]
sounds good, does that email address exist?

**Comment by ethulin** [comment]
Set to forward to your gmail
