### ISSUE TITLE
User profiles take up a ton of screen real estate on mobile

### ISSUE THREAD

**Issue by ethulin** [mefee/mefee#23]
Right now, the three elements to the profile link each get their own line, which takes a ton of real estate, making data entry really far down the page and requiring scrolling.

Suggested fix:

- Change "Current Profile:" to just "Profile:"
- Make "Add Profile" an item on the drop-down list, which when selected, prompts you for the name of the profile
- Put this on the same line as the temp F/C selection, and change that to just letters (so it becomes F and C rather than the words spelled out)

This should result in what is now 4 lines being condensed down into a single line.

**Comment by harry-peirse** [comment]
Will redo the UX tonight.

**Comment by harry-peirse** [comment]
Any suggestions on the new UX? Or we should close for now?
