### ISSUE TITLE
Switching back and forth between F to C to F messes up the recorded data

### ISSUE THREAD

**Issue by ethulin** [mefee/mefee#24]
After I switched from F to C to F, I got these values (as in, it seems like it changed my underlying values. Like it was re-rounding them or something.

<img width="859" alt="image" src="https://user-images.githubusercontent.com/19850662/78169424-5b223c80-741f-11ea-80a2-4bf031643551.png">

**Comment by harry-peirse** [comment]
It rounds them every time you toggle, I can change it to round just the display, but keep the underlying data. But I don't think this is high priority as it's an unusual use case.

**Comment by harry-peirse** [comment]
I think this is solved. Core data is never converted out of Farenheit (so american... urgh), Celsius conversion just happens for display purposes
