### ISSUE TITLE
Can not delete entries

### ISSUE THREAD

**Issue by ethulin** [mefee/mefee#30]
I am trying to delete these multiple 97 entries (was trying to enter 97.3), but clicking delete just reloads things, but keeps the data entry.

Also on Android.

**Comment by ethulin** [comment]
Also on Chrome in Windows

**Comment by harry-peirse** [comment]
I feat this is actually deleting a different data entry due to a mismatch from the sorting of whats displayed vs the sorting of the core data. That's what I get for coding drunk!

**Comment by harry-peirse** [comment]
fixed

**Comment by ethulin** [comment]
> I feat this is actually deleting a different data entry due to a mismatch from the sorting of whats displayed vs the sorting of the core data. That's what I get for coding drunk!

Oh no! Were you able to restore my old data?
