### ISSUE TITLE
Not able to get a dot above the red line regardless of temp

### ISSUE THREAD

**Issue by ethulin** [mefee/mefee#8]
Because recent readings are being incorporated into the average, it is basically impossible to get a dot above the red line.

For redline calculation, I suggest the following:
- Ignore any datapoint collected in the last 24hrs in determining redline
- Do not allow any redline value above 100.4. If temperature exceeds 100.4, change recommendation to contact physician

**Comment by harry-peirse** [comment]
seems pretty problematic! I'll ignore points from the last 24 hours from the bar calculation and we'll see what that does. We also need to consider if historical data contains a high temperature. Should we only look at the 20 least outlying data points for instance.

**Comment by harry-peirse** [comment]
I've capped the bar height to 100f, which is slightly more conservative, but inline with the UK NHS guidelines for fever (37.8 - https://www.nhsinform.scot/illnesses-and-conditions/infections-and-poisoning/fever-in-adults )

**Comment by harry-peirse** [comment]
data points in the last 24 hours are ignored.

**Comment by harry-peirse** [comment]
What to do when:
 - data points over 24 hours ago are high
 - low number of data points indicate bar over 100 (current functionality is to cap bar at 100)

**Comment by ethulin** [comment]
Not sure I totally get the situation. Is this an example?

Last two data points are within the last two hours, and they are above 100?

If so, it should indicate that you should contact a physician?

Basically, I think the logic flow is this:
- Take values more than 24hrs old. Calculate bar.
- If bar is is >100f, set bar to 100f
- IF current temp is over 100f, return see doctor msg
- IFELSE current temp is over bar (but less than 100f), return isolate msg
- ELSE return no msg

I am going to leave this open in case that doesn't answer your Q

**Comment by harry-peirse** [comment]
Thanks, that's clear. There's another case though, what if the historical data showed a fever? How will we know to ignore those points beyond 24 hours ago?

**Comment by harry-peirse** [comment]
rules you described above are implemented 🙇
